# Spring Boot Database and JPA Configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1000

# JSON Data File Path
json-data-file-path: /Users/youngwooyoon/YYW/GitHub/batch-insert-application/cfg_vdn.json

# VDN Center and Server Default Information
vdn.center-id: test-center-id
vdn.server-id: test-server-id